### PR TITLE
First commit from Karl; expect more later today

### PR DESCRIPTION
**Pull request by taylor13**
@balaji-gfdl @v-balaji I've just done a test pr which you should ignore.  I'll ping you when it's ready for merging (in a couple of hours).

### CODE REVIEW

**Comment by durack1** [comment]
@balaji-gfdl I think @taylor13 didn't effectively update this PR - "Karl Everyman Taylor" was the erroneous test commit that was going to be replaced

**Comment by taylor13** [comment]
@durack1 I have now tried to push again as follows:
```
[taylor13ml:Peer_reviewed/Balaji_WIP/wippaper] taylor13% git commit -am 'I have completed my edits.'
On branch Karls_edits
Your branch is up-to-date with 'origin/Karls_edits'.
nothing to commit, working tree clean
[taylor13ml:Peer_reviewed/Balaji_WIP/wippaper] taylor13% git push
Everything up-to-date
[taylor13ml:Peer_reviewed/Balaji_WIP/wippaper] taylor13% 
```
Any idea what I should try next?

**Comment by durack1** [comment]
@taylor13 try:
`git push -u origin HEAD:Karls_edits`

**Comment by taylor13** [comment]
get:
```
[taylor13ml:Peer_reviewed/Balaji_WIP/wippaper] taylor13% git push -u origin HEAD:Karls_edits
Branch Karls_edits set up to track remote branch Karls_edits from origin.
Everything up-to-date
```

**Pull request merged**
